### Generate bikes
POST {{rental}}/?bikes=20&bikeType=city
Accept: application/json

### List available bikes
GET {{rental}}/bikes
Accept: application/json

### Get bike status
GET {{rental}}/bikes/40208d8f-f338-4ba3-835e-b5026e6bde3e
Accept: application/json

### Request Bike
POST {{rental}}/requestBike?renter=BikeRider&bikeId=88951063-0504-4214-910b-769897623bb7
Accept: application/json

### Find payment ID
GET {{payment}}/findPayment?reference=97a265f8-3fc7-4507-885c-383ea6c3c0c2
Accept: application/json

### Accept payment
POST {{payment}}/acceptPayment?id=177cb079-d6ad-4991-82ed-3763d5dbd0cc
Accept: application/json

### Reject payment
POST {{payment}}/rejectPayment?id=d8be5441-2fde-4bc4-b784-f375734509f9
Accept: application/json

### Get bike status
GET {{rental}}/bikes/91480d9a-20e3-43a7-a88f-8712365a4f4c
Accept: application/json

### Return bike
POST {{rental}}/returnBike?location=New York&bikeId=4fea79be-3372-43e6-9c7b-35b4f0f5a605
Accept: application/json
