### Generate bikes
POST {{rental}}/?bikes=20&bikeType=city
Accept: application/json

### List available bikes
GET {{rental}}/bikes
Accept: application/json

### Get bike status
GET {{rental}}/bikes/40208d8f-f338-4ba3-835e-b5026e6bde3e
Accept: application/json

### Request Bike
POST {{rental}}/requestBike?renter=BikeRider&bikeId=a15032a4-2986-426d-bff7-b20ad2e96227
Accept: application/json

### Find payment ID
GET {{payment}}/findPayment?reference=9f667d2a-63dd-490c-a564-9d9f3a926f1d
Accept: application/json

### Accept payment
POST {{payment}}/acceptPayment?id=b62374db-248f-4629-8ecf-2a519a2b3d50
Accept: application/json

### Reject payment
POST {{payment}}/rejectPayment?id=d8be5441-2fde-4bc4-b784-f375734509f9
Accept: application/json

### Get bike status
GET {{rental}}/bikes/91480d9a-20e3-43a7-a88f-8712365a4f4c
Accept: application/json

### Return bike
POST {{rental}}/returnBike?location=New York&bikeId=a15032a4-2986-426d-bff7-b20ad2e96227
Accept: application/json
